### ISSUE TITLE
Access a single index

### ISSUE THREAD

**Issue by lunar-safari** [sathyarajv/pinecone#1]
The pinecone docs have this line;

`index = pinecone.Index("pinecone-index")`

I can't see anything in this project that does the same?

PS - this is a really great idea and will help loads of c# devs. Thanks!!!!

(you might want to flesh out the examples more too :)   )

**Comment by sathyarajv** [comment]
@lunar-safari You can also use 'Describe Index' method to get the details of given Index name.

**Comment by lunar-safari** [comment]
> @lunar-safari You can also use 'Describe Index' method to get the details of given Index name.


Thanks, this works well.

**Comment by lunar-safari** [comment]
I see in the Pinecone docs this

https://docs.pinecone.io/reference/describe_index_stats_post

This gives a breakdown of the namespaces and vectors inside an index.

Any plans for this to be added?
