### ISSUE TITLE
PineconeClient: Error Upserting: The SSL connection could not be established, see inner exception.

### ISSUE THREAD

**Issue by lunar-safari** [sathyarajv/pinecone#2]
Getting this error when Upserting.

**Comment by sathyarajv** [comment]
@lunar-safari Can you share more details or screenshot  to check this issue.?

**Comment by lunar-safari** [comment]
Hi, I have resolved this issue. When the Upsert method asked for 'project name' I was putting in the name ie 'My Project'. The correct way is the project id which looks a little more like '3JH7h6tF' or something like that.
So I successfully upserted a vector. 
Thanks
